import re

with open('src/utils/exportImport.ts', 'r', encoding='utf-8') as f:
    content = f.read()

content = content.replace("REPEAT_LABELS_IT", "REPEAT_LABELS_EN")
content = content.replace("CREATO IL:", "CREATED AT:")
content = content.replace("GRUPPO ID:", "GROUP ID:")
content = content.replace("DESCRIZIONE & NOTE:", "DESCRIPTION & NOTES:")
content = content.replace("(Nessuna nota descrittiva inserita)", "(No descriptive note provided)")
content = content.replace("Documento generato da Notula™ Memo Engine • Ideazione & Sviluppo Ing. Mario Fantini", "Document generated by Notula™ Memo Engine • Concept & Development Ing. Mario Fantini")
content = content.replace("Copyright © 2026 Tutti i Diritti Riservati", "Copyright © 2026 All Rights Reserved")
content = content.replace("Inserisci la Master Password per decifrare il file importato:", "Enter the Master Password to decrypt the imported file:")
content = content.replace("Master Password richiesta per file cifrati.", "Master Password required for encrypted files.")
content = content.replace("Senza titolo", "Untitled")
content = content.replace("Puntuale", "One-time")
content = content.replace("Ricorrente", "Recurring")
content = content.replace("Scadenza: ", "Expiration: ")

with open('src/utils/exportImport.ts', 'w', encoding='utf-8') as f:
    f.write(content)

