import os
import re

def safe_replace(filepath, it, en):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 1. JSX Text >text<
    # We replace >it< with >{settings.language === 'en' ? 'en' : 'it'}<
    # Note: re.escape(it)
    pattern1 = r'>\s*(' + re.escape(it) + r')\s*<'
    replacement1 = r'>{settings.language === "en" ? "' + en + '" : "' + it + '"}<'
    content = re.sub(pattern1, replacement1, content)
    
    # 2. JSX attributes e.g., title="text"
    pattern2 = r'([a-zA-Z]+)="(' + re.escape(it) + r')"'
    replacement2 = r'\1={settings.language === "en" ? "' + en + '" : "' + it + '"}'
    content = re.sub(pattern2, replacement2, content)

    # 3. Bare text next to expressions, e.g. } text {
    pattern3 = r'}\s*(' + re.escape(it) + r')\s*{'
    replacement3 = r'} {settings.language === "en" ? "' + en + '" : "' + it + '"} {'
    content = re.sub(pattern3, replacement3, content)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

replacements = {
    "Memo Puntuali (Bordo Cromatico Rettangolare)": "One-time Memos (Rectangular Color Border)",
    "Memo Ricorrenti (Pallino Pieno &bull;)": "Recurring Memos (Solid Dot &bull;)",
    "Quando crei o cloni un memo ricorrente (es. per 15 giorni o 12 mesi), Notula™ assegna a tutti i memo della serie lo stesso ": "When you create or clone a recurring memo (e.g., for 15 days or 12 months), Notula™ assigns the same ",
    ". Se modifichi il memo di oggi (titolo, note o livello di sicurezza), le modifiche vengono propagate ": ". If you modify today's memo (title, notes, or security level), changes are ",
    ", preservando le rispettive date del calendario!": ", preserving their respective calendar dates!",
    "Effetto: Notula™ ricalcola all'istante la chiave crittografica hardware; da quel momento tutti i nuovi memo cifrati, le modifiche e i file di sincronizzazione su Google™ Drive useranno la nuova Master Passphrase.": "Effect: Notula™ instantly recalculates the hardware cryptographic key; from then on, all new encrypted memos, modifications, and synchronization files on Google™ Drive will use the new Master Passphrase.",
    "Puoi usare Notula™ su ": "You can use Notula™ on ",
    ": aprendo l'app e cliccando su ": ": open the app, click ",
    " ritrovi tutti i tuoi memo sincronizzati.": " and find all your synchronized memos.",
    "Premi il pulsante ": "Press the ",
    " per filtrare per testo, per data esatta, per ID memo o per categoria (solo puntuali, solo ricorrenti, solo scaduti).": " button to filter by text, exact date, memo ID, or category (only one-time, only recurring, only expired).",
    "Nel sottomenu ": "In the ",
    " puoi cancellare memo per singolo ID, per intero anno, per mese, per data, per ricorrenza o solo quelli già scaduti.": " submenu, you can delete memos by single ID, whole year, month, date, recurrence, or just expired ones.",
    "1. CREAZIONE &amp; MODIFICA MEMO (add &bull; edit)": "1. CREATE &amp; EDIT MEMOS (add &bull; edit)",
    "Modifica memo (aggiorna in automatico tutti i memo con lo stesso groupID)": "Edit memo (automatically updates all memos with the same groupID)",
    "Esporta singolo memo nel formato indicato": "Export single memo in the specified format",
    "4. VISUALIZZAZIONE ED ELENCO MEMO (ls &bull; list)": "4. VIEW AND LIST MEMOS (ls &bull; list)",
    "Mostra tutti i memo presenti": "Show all memos",
    "Mostra tutti i memo della serie collegata": "Show all memos in the linked series",
    "Mostra esclusivamente i memo scaduti": "Show only expired memos",
    "1. Elimina singolo memo per ID": "1. Delete single memo by ID",
    "Elimina tutti i memo scaduti": "Delete all expired memos",
    "Elimina TUTTI i memo (pulizia totale)": "Delete ALL memos (total wipe)",
    "memo in archivio locale • Cartella remota:": "memos in local storage • Remote folder:",
    "Scheda di dettaglio per memo ID:": "Detail card for memo ID:",
    "Documento generato da Notula™ Memo Engine &bull; Ing. Mario Fantini": "Document generated by Notula™ Memo Engine &bull; Eng. Mario Fantini",
    "I memo contrassegnati e i pacchetti di sincronizzazione su Google™ Drive sono protetti con chiave crittografica PBKDF2 a 256-bit.": "Marked memos and Google™ Drive sync packages are protected with a 256-bit PBKDF2 cryptographic key.",
    "Nessuna Master Passphrase attiva. I memo sono memorizzati localmente in chiaro.": "No active Master Passphrase. Memos are stored locally in plain text.",
    "Maschera visivamente i testi dei memo per proteggerli da occhiate indiscrete": "Visually masks memo texts to protect them from prying eyes",
    "Memo ricorrente oggi (Pallino Blu)": "Recurring memo today (Blue Dot)",
    "Memo ricorrente passato (Pallino Grigio)": "Past recurring memo (Gray Dot)",
    "Memo ricorrente futuro (Pallino Verde)": "Future recurring memo (Green Dot)",
    "Memo del": "Memos for",
    "memo archiviati per questa data": "memos stored for this date",
    "Nessun memo presente per il": "No memos present for",
    "Nuovo Memo in Notula™": "New Memo in Notula™",
    "Crea memo puntuale o ricorrente con opzione AES-256": "Create one-time or recurring memo with AES-256 option",
    "Serie Ricorrente Collegata:": "Linked Recurring Series:",
    "Le modifiche a titolo, descrizione e sicurezza verranno sincronizzate ": "Changes to title, description, and security will be synchronized ",
    " su tutti i memo della serie.": " across all memos in the series.",
    "Titolo del Memo *": "Memo Title *",
    "Salva Modifiche": "Save Changes",
    "Archivia in Notula™": "Store in Notula™",
    "Cerca nei Memo (Notula Search)": "Search Memos (Notula Search)",
    "Cerca memo per titolo, testo, data esatta o ID": "Search memos by title, text, exact date, or ID",
    "Trovati ": "Found ",
    " memo corrispondenti": " matching memos",
    "Nessun memo corrisponde ai criteri specificati.": "No memos match the specified criteria.",
    "Esporta singolo memo (JSON/XML/MD/TXT)": "Export single memo (JSON/XML/MD/TXT)",
    "ID Memo in conflitto:": "Conflicting Memo ID:",
    "Elenco Memo (GEM a-g)": "Memo List (GEM a-z)",
    "Visualizza e filtra i memo per categoria": "View and filter memos by category",
    "Nessun memo presente per la categoria selezionata.": "No memos present for the selected category."
}

for root, _, files in os.walk('src/components'):
    for file in files:
        if file.endswith('.tsx') or file.endswith('.ts'):
            filepath = os.path.join(root, file)
            for it, en in replacements.items():
                safe_replace(filepath, it, en)
